version: '3.7'

# 指定這個 docker compose 要啟動的服務
services:
  postgres:
    container_name: eCommerce_postgresql       # 指定 container 的名稱
    image: postgres:14.2                 # container 使用的 image
    restart: always                      # 
    environment:                         # 指定環境變數
    - POSTGRES_USER=eCommerce
    - POSTGRES_PASSWORD=P@ssword
    - POSTGRES_HOST_AUTH_METHOD=trust
    - POSTGRES_DB=eCommerce                    # 指定 PostgreSQL 預設資料庫，如不指定則會使用 POSTGRES_USER 的值建立預設資料庫
    ports:                               # 指定本機的 Port 對應 Container 的 Port, 格式: HOST:CONTAINER
    - 5432:5432
    volumes:                             # 掛載 docker 的 volume
    #- ./db/:/docker-entrypoint-initdb.d  # ./db/ 指相對路徑下 db 這個資料夾；/docker-entrypoint-initdb.d 指 docker 的進入點
    - db:/var/lib/postgresql/data        # db 指向 volume 名稱

volumes:
  db:
    driver: local